const prompt = require('prompt-sync')();

let number = Math.floor((Math.random()*100)+1);
let chance = 0;//initial value of chance taken to guess a no.
let guess;

console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by the computer ,then you win...\n ")

guess = prompt("Enter a number between 1 to 100\n");
++chance;//to increament the no of chances to be taken

do{
    guess = Number.parseInt(guess);
    if(guess>number){
        console.log("Number enteres is greater");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chance;
    continue;
    }
    else if(number<guess){
        console.log("Number enteres is Smallerer");
        guess = prompt("Enter again!!");
        guess = Number.parseInt(guess);
        ++chance;
        continue;
    }

}while(guess != number);

let score =  100 - chance;

console.log("\n Congratulation 🥳🥳\n The number generated was",number +"and you guesses it right\n your final score is" , score);